# Generated by Django 4.2.5 on 2023-10-08 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
